### ISSUE TITLE
Upgrade laravel ke versi 9

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#256]
1. Tentukan jadwal upgrade menggunakan shift 
2. Tentukan kapan melakukan upgrade https://laravelshift.com/
3. Testing Pantau dengan laravel baru yang di upgrade https://laravelshift.com/

**Comment by pandigresik** [comment]
> 1. Tentukan jadwal upgrade menggunakan shift
> 2. Tentukan kapan melakukan upgrade https://laravelshift.com/
> 3. Testing Pantau dengan laravel baru yang di upgrade https://laravelshift.com/

1. Bisa dilakukan pada 05 Pebruari 2023
2. Setelah dilakukan pembayaran
