### ISSUE TITLE
Buat layout & susunan dasbor menggunakan AdminLTE

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#266]
Saat ini tampilan pantau seperti berikut ini : 

![image](https://github.com/OpenSID/pantau/assets/59082428/310da7a5-213b-46b6-99b0-695bf2407379)

Aplikasi Pantau bertujuan memberi informasi pemantauan penggunaan aplikasi yg dikelola OpenDesa.

Dasbor saat ini hanya memperlihatkan pemantauan OpenSID. Dasbor ini perlu dirancang ulang untuk memenuhi kebutuhan sbb:

1. Menampilkan status setiap aplikasi kelolaan OpenDesa
2. Tampilan yg menarik dan mudah dipahami
3. Bisa menelusuri rincian status yang ditampilkan

Status aplikasi untuk ditampilkan:

1. OpenSID
    1. Jumlah desa aktif
    2. Jumlah desa aktif menggunakan PBB
    3. Jumlah desa aktif menggunakan LayananDesa
    4. Jumlah desa aktif menggunakan KelolaDesa
    5. Jumlah desa aktif menggunakan Anjungan Mandiri
    6. Grafik tren 1-5 di atas untuk enam bulan terakhir (per bulan)
    7. Desa pengguna baru dalam 7 hari terakhir
2. OpenDK
    1. Jumlah pengguna OpenDK
    2. Grafik tren untuk enam bulan terakhir
    3. Pengguna baru dalam bulan terakhir
4. Dasbor SiapPakai
    1. Jumlah pengguna Dasbor SiapPakai
5. OpenKab
    1. Jumlah pengguna OpenKab
    
    
    dari kebutuhan diatas silahkan buat tampilan dasbor dalam bentuk statis terlebih dahulu kebutuhan teknis seperti berikut : 

- [ ] Buat tampilan dasbor statis menggunakan Admin LTE
- [ ] Sesuaikan Dasboar dengan kebutuhan diatas
- [ ] Kirim PR dengan FIle admin LTE saja
- [ ] Tidak perlu diterapkan ke pantau terlebih dahulu hanya font-end statis saja

**Comment by vaifalifkhan17** [comment]
M.Vaif - Magang

**Comment by Arue434** [comment]
Arfi Indra - magang
