### ISSUE TITLE
error nambah desa baru pada pantau

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#290]
Saat nambah desa baru error seperti berikut ini : 
![image](https://github.com/OpenSID/pantau/assets/59082428/47a6b487-0571-4e11-b0f2-94bc92bd3a2b)

**Comment by agungsugiarto** [comment]
Saya tidak mengalami error di lokal, dan branch dev. Bisa bantu kirim backup lognya mas @vickyrolanda ?
