### ISSUE TITLE
Rancang ulang tampilan pantau

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#296]
![PANTAU](https://github.com/OpenSID/pantau/assets/59082428/6bd3e49c-5a59-4be9-8b55-d0c034d0f80a)
Rancangan ulang tampilan pantau, halaman ini untuk halaman dasbor pantau yang mengambarkan penggunaan dari keseluruhan aplikasi.

Lalu nanti dimasing-masing menu aplikasi juga terdapat dasbor pantau seperti berikut ini : 
![OpenSID-v2](https://github.com/OpenSID/pantau/assets/59082428/cdec2bc9-4b38-4b88-b3c4-7263a0a79433)

dari tampilan diatas sebagian besar data sudah ada pada pantau saat ini hanya penyesuaian tampilan dan pemanggilan data yang realtime.

[PANTAU v.1.pdf](https://github.com/user-attachments/files/15601549/PANTAU.v.1.pdf)

untuk Issue ini pengerjaannya pada pembuatan templatenya saja untuk implementasi dapat dilakukan diissue terpisah.

- [x] #297
- [x] #298
- [x] #299

**Comment by pandigresik** [comment]
https://t.me/c/1890895110/9035
