### ISSUE TITLE
Cek tarik gagal tarik data

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#301]
ada permasalahan lagi di pantau dan layanan :
1. gagal tarik data (ada perubahan nama desa dari purso seharusnya purwo, sudah diperbaiki, tapi gagal tarik data di layanan)
1. di pantau kalau mengubah desa yang pernah diubah tidak bisa, contoh :
desa seknas (Tangjungharo sikabu-kabu Padang Panjang akan dikembalikan lagi ke Tj Haro Sikabu-kabu Pd Panjang, dan ternyata tidak bisa)

![Uploading image.png…]()

**Comment by pandigresik** [comment]
perbaikan tarik data pada aplikasi layanan https://github.com/OpenSID/Layanan_OpenDESA/pull/591
