### ISSUE TITLE
Informasi Pengguna Per Wilayah (poin 6) - Halaman OpenSID

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#337]
**Informasi Pengguna Per Wilayah (poin 6):**
![image](https://github.com/user-attachments/assets/5805212f-9221-43f3-acae-8f6952555d2a)

Bagian ini memberikan rincian jumlah pengguna OpenSID berdasarkan provinsi, kabupaten, kecamatan, dan desa/kelurahan. Ini membantu dalam analisis penyebaran pengguna OpenSID di berbagai tingkatan wilayah.

**Comment by pandigresik** [comment]
Sepertinya ini sudah ada informasi tersebut
