### ISSUE TITLE
Penerapan Daftar Versi Aplikasi LayananDesa Berdasarkan API

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#379]
![image](https://github.com/user-attachments/assets/128e203c-ded8-4ff0-8845-6881af924e4a)

Tampilkan versi LayananDesa dan jumlah pengguna yang pasang, untuk layanan desa maka hanya ada 1 kolom saja dengan judul terpasang tidak perlu Online & offline. 

data versi di kirim melalui API dimana versi LayananDesa selalu sama dengan versi API .

**Comment by pandigresik** [comment]
![image](https://github.com/user-attachments/assets/0bf9244e-61fe-4de7-bd29-f0b9a36a64b7)

Saat ini layananDesa belum mengirim data versi ke pantau
