### ISSUE TITLE
Ubah ID dengan No Urut pada halaman pengguna aplikasi LayananDesa

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#394]
![image](https://github.com/user-attachments/assets/b234dfc5-8a3b-4213-bafc-6fe523f4d279)

**Comment by yogiperdana** [comment]
Ini maksudnya yang mana mas @vickyrolanda

**Comment by yogiperdana** [comment]
Status diubah siap review karena menunggu issue dilengkapi

**Comment by pandigresik** [comment]
Id tersebut adalah id dari device, jika diubah menjadi nomer urut maka ada kemungkinan akan ada data yang seolah-olah kembar. Misalkan di hari yang sama ada 50 pengguna di desa yang sama melakukan instalasi aplikasi layanan desa, maka secara tampilan nomer 1 sd 50 akan menjadi kembar
