### ISSUE TITLE
Sesuaikan halaman admin seperti tampilan dasbor namun perlu penyesuaian data

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#426]
Details issue masih dikerjakan sesuai data & tampilan penyesuaian pada halaman admin.

**Comment by pandigresik** [comment]
mas @vickyrolanda apakah issue ini timbul dikarenakan https://t.me/c/1180597796/15352 ? Jika iya saya rasa PR https://github.com/OpenSID/pantau/pull/432 sudah cukup, sehingga tidak perlu kita rombak lagi dashboard pantau untuk halaman admin
