### ISSUE TITLE
Penyesuaian statistik pada pantau agar terlihat lebih infografik

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#440]
![image](https://github.com/user-attachments/assets/259a1fa8-01c5-4526-b676-c6092d382909)
Saat ini tampilan statistik pada dasbor terlihat tidak rapi karena terkait data maka perlu ubah menjadi seperti berikut ini : 
 
![image](https://github.com/user-attachments/assets/97265c35-8f49-4343-bb8b-677100928e3c)

Retensi data dari bawah buat 0,300, 600, 1000 lalu kelipatan1000 keatas agar yang memiliki statistik data renda masih bisa terlihat diblock statistik

**Comment by agungsugiarto** [comment]
mas @vickyrolanda chartnya diubah tipe bar ?
