### ISSUE TITLE
Cek kesesuaian data pada dabor saat ini masih belum valid karena data yang terpasang pada dasbor masih 0

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#441]
![image](https://github.com/user-attachments/assets/675d6540-6c9b-4e20-aa93-2b56a391ecea)

jika dilihat pada pantau data yang kerja sama semua data yang terpasang masih 0 sehingga perlu dicek agar fungsi berjalan normal.

**Comment by agungsugiarto** [comment]
mas @vickyrolanda saya coba tidak ada masalah di apinya?

api postman

![Image](https://github.com/user-attachments/assets/4470bc57-a793-4600-a028-6ad8688ac614)

terupdate di database

![Image](https://github.com/user-attachments/assets/4a2f2e30-fec2-41c5-a961-efd930b5aa5d)

Perlu diperiksa di client aplikasi yang mengirim openkab!
