### ISSUE TITLE
halaman kelola desa tidak menampilkan data yang akurat atau data tidak tertangkap pada pantau

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/pantau#462]
![image](https://github.com/user-attachments/assets/91f77885-96c0-4a57-95df-8a0bd3e48731)

dilihat dari  gambar tidak ada data padahal pengguna sudah ada karena ada yang lapor : 
lihat referensi penerapan pengambilan datanya di PR https://github.com/OpenSID/mobile-admin-opensid/pull/82

**Comment by misarianto** [comment]
untuk API track kelola desa sudah benar ternayata alamat API pada Flutter belum Set mas @vickyrolanda
